version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/

hooks:
  ApplicationStart:
    - location: app-start.sh
      timeout: 300

  BeforeInstall:
    - location: before-install.sh
      timeout: 300

  AfterInstall:
    - location: after-install.sh
      timeout: 300

  ApplicationStart:
    - location: app-start.sh
      timeout: 300

  ApplicationStop:
    - location: app-stop.sh
      timeout: 300
